name: Linode

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
          host: ${{ secrets.LINODE_HOST }}
          user: root
          key: ${{ secrets.LINODE_SSHKEY}}
